version: "3"

services:
  database:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: man
      POSTGRES_DB: blober
      PGDATA: /var/lib/postgresql/data/db
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    container_name: minio_server
    command: server data:/mnt/data
    restart: always
    environment:
      MINIO_ACCESS_KEY: yourMinioAccessKey
      MINIO_SECRET_KEY: yourMinioSecretKey
    volumes:
      - data:/mnt/data
    ports:
      - "9000:9000"

  bloberio:
    build: .
    container_name: blober_io
    restart: on-failure
    depends_on:
      - minio
      - database
    ports:
      - "9008:9008"
    volumes:
      - data:/var/blober
volumes:
  data:
    external: true